pipeline {
    agent any
    
    stages {
        stage('Build Docker image') {
            steps {
                sh """
                  cd Docker
                  pwd
                  ls -la
                  docker build -t mydockerimage:latest .
                  docker images
                   """
            }
        }
    }
}
