pipeline {
    agent any
    
    stages {
        stage('Build Docker image') {
            steps {
                cd "${WORKSPACE}/Docker"
                sh 'docker build -t mydockerimage:latest .'
                sh 'docker images'
            }
        }
    }
}
