pipeline {
    agent any
    
    stages {
        stage('Build Docker image') {
            steps {
                sh """
                  cd Docker
                  pwd
                  ls -la
                  echo $PATH
                  docker --version
                   """
            }
        }
    }
}
